### ISSUE TITLE
PDF Exporter not on new prod server

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#349]
No PDF exports work :(

**Comment by thehabes** [comment]
Further details from catalina.out

textdisplay.TagFilter.replaceTagsWithPDFEncoding null
 java.io.IOException: /usr/Junicode.ttf not found as file or resource.
 at textdisplay.TagFilter.replaceTagsWithPDFEncoding(TagFilter.java:189)
 at export.exportPDF(export.java:96)
 at export.doGet(export.java:72)

**Comment by thehabes** [comment]
Maybe try to put the junicode files that are on the prod server's /usr/ directory into 165.134.105.25's /usr/ directory

**Comment by thehabes** [comment]
Ugh, don't have sudo on the new prod, so I cannot create files in the /usr/ directory, which is how we fix this.  Should I ask ITS :)

**Comment by thehabes** [comment]
I have asked for sudo privileges on this server.  Until I receive them, we will be unable to perform the tasks necessary to have TPEN28 on this server.  I am unable to access the folders on root (the images, PDF exporter and mailer) and unable to access the Tomcat instances to upload new .war files and unable to start or stop the tomcat instances.

**Comment by thehabes** [comment]
At this point, I am at a work stoppage waiting for it to be cleared.  See the email below:

I have reached a work stoppage where I cannot continue.  I am at the point where I am deploying the new TPEN, but it is supposed to be on the new prod server (f-vl-cdh-prd-01) since we are working towards getting rid of the other servers.  Therefore, I have to test in f-vl-cdh-prd-01's environment before we go forward with the official launch.  I have tested the bug fixes in my dev environment and am ready to upload a new version with bug fixes I found from testing onto f-vl-cdh-prd-01.

I need to move some files into the /usr/ directory to close a ticket and deploy the new .war file in tomcat to test the others. I requested to have those files moved on 2/10, but at this date they are still unmoved.  If someone with sudo access were available to do this, we could move the files, test and close this in a matter of minutes.  The tomcat manager is not working and since I only have access to my directory, I am unable to perform the deployment so all other tickets remain untested.

Unfortunately, Sam is out today and may not respond to E-mails, and I have been told he is in charge of these types of things when it comes to the CDH, so I am wondering if someone in ITS can help me so I can move forward with this.  It is frustrating to know I have everything ready and everything on the server, but lack of permissions is indefinitely extending my launch schedule for this, and today has made it so that I can no longer work. 

Thank you, and please let me know if you are available to assist us.
