### ISSUE TITLE
Import Buttons From Schema

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#573]
I can successfully link a schema, but I cannot get any buttons from it.  Errors include

```java
 java.io.FileNotFoundException: /usr/web/schema2.xsl (No such file or directory)
01-Mar-2021 12:05:16.385 SEVERE [ajp-nio-8109-exec-279] textdisplay.TagButton.getTagsFromSchema null
 net.sf.saxon.s9api.SaxonApiException: Failed to compile stylesheet. 1 error detected.
        at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:149)
        at textdisplay.TagButton.xslRunner(TagButton.java:923)
        at textdisplay.TagButton.getTagsFromSchema(TagButton.java:943)
        at org.apache.jsp.buttonSchemaImport_jsp._jspService(buttonSchemaImport_jsp.java:465)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
```

```java
java.lang.NullPointerException
	org.apache.jsp.buttonSchemaImport_jsp._jspService(buttonSchemaImport_jsp.java:439)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
```

Attempted schemas
- https://www.loc.gov/standards/xlink/xlink.xsd
- https://www.loc.gov/standards/alto/v4/alto-4-2.xsd
- https://sites.google.com/site/tpenschema/relax/superpsalterium.rng (not found)

**Comment by thehabes** [comment]
Leave it in broken right now because that's how it is.  Not worth taking out, wait for a user report before caring about it.
