### ISSUE TITLE
Delete Project

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#576]
```Java
02-Mar-2021 12:46:15.249 SEVERE [ajp-nio-8109-exec-327] textdisplay.Project.firstPage Error loading first page for project 0
 java.lang.ArrayIndexOutOfBoundsException: 0
        at textdisplay.Project.firstPage(Project.java:1522)
        at org.apache.jsp.project_jsp._jspService(project_jsp.java:790)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)

```
Getting this every time in the logs.

**Comment by cubap** [comment]
:243 an isAdmin check that shouldn't be there...

**Comment by cubap** [comment]
Delete project never calls `firstPage()` but it is right before it in the class so something odd may be happening...

**Comment by cubap** [comment]
on project.jsp, `firstPage()` only fires if there is no "p" parameter, which is the trouble.
